### ISSUE TITLE
Num of spaces for nested list

### ISSUE THREAD

**Issue by nguyenducbinh96** [sstur/draft-js-export-markdown#17]
Hi Simon.
Thank you so much for your lib.

I found **4spaces** is required for a nested list as described in the specs
http://markdown-guide.readthedocs.io/en/latest/basics.html#lists-nested

However, in line 103 and 120 of stateToMarkdown.js, only **2spaces** are being used.

`var indent = ' '.repeat(block.depth * 2);`

**Comment by sstur** [comment]
Closed by #18.
