### ISSUE TITLE
Question of the scope of the exporter

### ISSUE THREAD

**Issue by jaaberg** [sstur/draft-js-export-markdown#2]
@sstur Is this meant for basic rich text editors with links? 

Would be nice to have a solution that also supports mentions, hashtags, images etc that is often used in editors these days. Or some kind of way to define our own rules.

**Comment by sstur** [comment]
Sorry for the late reply. Almost missed this one.

This is meant to evolve with [react-rte](https://react-rte.org/) which only supports basic styling and links at this time. Inline images are being worked on currently and there is more coming soon.

I'm happy to take pull requests to make this module better and more pluggable.

Thanks!
